### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
vector = np.random.rand(10)
print(f"vector values:{vector}")
print(f"vector shape:{vector.shape}")


vector values:[0.99540067 0.66720784 0.66374311 0.03166816 0.56888477 0.56012271
 0.54773352 0.72012859 0.06240037 0.58883699]
vector shape:(10,)


In [3]:
matrix = np.array([[11, 14, 17],
                  [20, 23, 26],
                  [29, 32, 35]])
print(f"matrix values: {matrix}")
print(f"matrix shape: {matrix.shape}")


matrix values: [[11 14 17]
 [20 23 26]
 [29 32 35]]
matrix shape: (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [8]:
vector_10 = vector + 10
vector_round = np.round(vector_10, 2)
print(vector_round)

[11.   10.67 10.66 10.03 10.57 10.56 10.55 10.72 10.06 10.59]


In [9]:
matrix_mult = 2 * matrix
print(matrix_mult)

[[22 28 34]
 [40 46 52]
 [58 64 70]]


In [13]:
vector_quadro = vector**2
print(vector_quadro)
#тут підношу до степеня початковий vector. Якщо малося наа увазі робити перетворення вектора, який отримали у завданні 2.1, то наступний код:
vector_quadro = vector_round**2
print(vector_quadro)

[0.9908225  0.4451663  0.44055492 0.00100287 0.32362988 0.31373745
 0.30001201 0.51858519 0.00389381 0.346729  ]
[121.     113.8489 113.6356 100.6009 111.7249 111.5136 111.3025 114.9184
 101.2036 112.1481]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [18]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [16]:
result_matrix = np.dot(B,A) #множу В на А, щоб отримати матрицю 2х2

print(result_matrix)

[[0.7281 0.5202]
 [0.2034 0.2846]]


In [23]:
result_matrix = np.dot(result_matrix, C)
print(result_matrix)

[[0.5202]
 [0.2846]]


In [25]:
#результуюча матриця матиме розмір 2 х 1
result_matrix = np.dot(D, result_matrix) #множимо D на result_matrix, так як навпаки помножити не можемо через несумісність розмірів
print(result_matrix)


[[0.2846]
 [0.5202]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [27]:
#транспонуємо матрицю
result_matrix_T = result_matrix.T
print(result_matrix_T)

[[0.2846 0.5202]]


In [28]:
#транспонуємо вектор. Різниці немає, так як вектор - це одномірний масив 
vector_T = vector.T
print(vector_T)

[0.99540067 0.66720784 0.66374311 0.03166816 0.56888477 0.56012271
 0.54773352 0.72012859 0.06240037 0.58883699]


In [31]:
#перетворюємо вектор у двовимірний і порівнюємо розмір початкового вектора і вектора після перетворення
column_vector = np.expand_dims(vector, axis=1)
print("Вектор після застосування np.expand_dims з axis=1:")
print(column_vector)
print(f"vector shape:{vector.shape}")
print(f"column_vector shape: {column_vector.shape}")

Вектор після застосування np.expand_dims з axis=1:
[[0.99540067]
 [0.66720784]
 [0.66374311]
 [0.03166816]
 [0.56888477]
 [0.56012271]
 [0.54773352]
 [0.72012859]
 [0.06240037]
 [0.58883699]]
vector shape:(10,)
column_vector shape: (10, 1)


In [33]:
#транспонуємо column_vector
column_vector_T = column_vector.T
print(column_vector_T)
print(f"column_vector_T shape: {column_vector_T.shape}")

[[0.99540067 0.66720784 0.66374311 0.03166816 0.56888477 0.56012271
  0.54773352 0.72012859 0.06240037 0.58883699]]
column_vector_T shape: (1, 10)
